version: '3.8'
services:
  lamp-apache:
    container_name: docker-lamp-apache
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    restart: always
    ports:
      - '8080:80'
      - '8083:443'
    depends_on:
      - lamp-mysql

  lamp-mysql:
    image: mysql:5.7.36
    container_name: docker-lamp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./temp/docker/mysql:/var/lib/mysql
    restart: always
